# Generated by Django 4.0.5 on 2022-07-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_users_link_cut_link_alter_users_link_long_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_link',
            name='cut_link',
        ),
        migrations.AlterField(
            model_name='users_link',
            name='long_link',
            field=models.TextField(verbose_name='Long link'),
        ),
    ]
