# Generated by Django 4.0.5 on 2022-07-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_users_link_cut_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_link',
            name='cut_link',
            field=models.TextField(blank=True, verbose_name='Cut link'),
        ),
    ]
