# Generated by Django 4.1.2 on 2022-10-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_users_link_cut_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_link',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='Site name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users_link',
            name='qr',
            field=models.ImageField(default=2, upload_to='media\\qr'),
            preserve_default=False,
        ),
    ]
