# Generated by Django 4.1.2 on 2022-10-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_users_link_name_users_link_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_link',
            name='qr',
            field=models.ImageField(upload_to=''),
        ),
    ]
